"use client";
import React,{useContext,useEffect,useState} from "react";
import { ArrowLeft, Heart, Minus, Plus, MessageCircle, ShieldCheck, ShoppingBag, Star, Truck, X, Ruler, Share2 } from "lucide-react";
import { AppContext } from "@/components/store/AppProvider";

export default function ProductDetailPage(){
  const {selectedProduct,addToCart,setActiveTab,wishlist,toggleWishlist}=useContext(AppContext);
  const [activeImage,setActiveImage]=useState('');const [size,setSize]=useState('');const [color,setColor]=useState('');const [qty,setQty]=useState(1);const [guide,setGuide]=useState(false);
  useEffect(()=>{if(selectedProduct){setActiveImage(selectedProduct.gallery?.[0]||selectedProduct.image);setSize(selectedProduct.sizes?.[0]||'Standard');setColor(selectedProduct.colors?.[0]||'Classic');setQty(1)}},[selectedProduct]);
  if(!selectedProduct)return null;
  const saved=wishlist.includes(selectedProduct.id);const msg=encodeURIComponent(`Assalam-o-Alaikum Kamalia, I would like to order:\n${selectedProduct.name}\nColor: ${color}\nSize: ${size}\nQuantity: ${qty}\nPrice: Rs. ${selectedProduct.price.toLocaleString()}`);
  return <div className="section-wrap py-7 md:py-10">
    <button onClick={()=>setActiveTab('shop')} className="flex items-center gap-2 text-xs font-bold text-[#68726c] hover:text-[#0b201b] mb-6"><ArrowLeft size={15}/> Back to collection</button>
    <div className="grid lg:grid-cols-2 gap-8 lg:gap-12">
      <div><div className="relative aspect-[4/5] rounded-[28px] overflow-hidden bg-[#eee9df] border border-[#e9e3d8]"><img src={activeImage} alt={selectedProduct.name} className="w-full h-full object-cover"/><div className="absolute left-4 top-4 rounded-full bg-white/90 backdrop-blur px-3 py-1.5 text-[9px] font-black uppercase tracking-wider text-[#0b201b]">Kamalia Original</div><button onClick={()=>toggleWishlist(selectedProduct.id)} className="absolute right-4 top-4 w-10 h-10 rounded-full bg-white/90 flex items-center justify-center"><Heart size={17} fill={saved?'currentColor':'none'} className={saved?'text-[#9b3145]':''}/></button></div><div className="flex gap-3 mt-3 overflow-x-auto scrollbar-hide">{(selectedProduct.gallery||[selectedProduct.image]).map((img:string,i:number)=><button key={img+i} onClick={()=>setActiveImage(img)} className={`shrink-0 w-20 h-24 rounded-xl overflow-hidden border-2 ${activeImage===img?'border-[#b7924b]':'border-transparent'}`}><img src={img} alt="" className="w-full h-full object-cover"/></button>)}</div></div>
      <div className="lg:py-3">
        <div className="eyebrow">{selectedProduct.category} · {selectedProduct.fabric}</div><h1 className="serif text-3xl md:text-5xl leading-tight mt-2">{selectedProduct.name}</h1>
        <div className="flex flex-wrap items-center gap-3 mt-4 text-xs"><span className="flex items-center gap-1 font-bold"><Star size={14} fill="currentColor" className="text-[#c49643]"/>{selectedProduct.rating}</span><span className="text-[#8a918c]">{selectedProduct.reviewsCount} verified reviews</span><span className="text-[#4d7359] font-bold">In stock · {selectedProduct.stock} left</span></div>
        <div className="mt-6 flex items-end gap-3"><span className="text-3xl font-black text-[#0b201b]">Rs. {selectedProduct.price.toLocaleString()}</span>{selectedProduct.originalPrice&&<span className="text-sm text-[#8a918c] line-through">Rs. {selectedProduct.originalPrice.toLocaleString()}</span>}</div>
        <p className="mt-5 text-sm leading-7 text-[#5f6862]">{selectedProduct.description}</p>
        <div className="gold-line my-7"/>
        <div className="space-y-6">
          <div><div className="flex items-center justify-between mb-3"><span className="text-xs font-black">Colour <span className="font-normal text-[#7b827d]">— {color}</span></span></div><div className="flex flex-wrap gap-2">{selectedProduct.colors.map((c:string)=><button key={c} onClick={()=>setColor(c)} className={`rounded-full border px-3.5 py-2 text-[10px] font-bold ${color===c?'border-[#0b201b] bg-[#0b201b] text-white':'border-[#d8d0c1] bg-white text-[#4d5952]'}`}>{c}</button>)}</div></div>
          <div><div className="flex items-center justify-between mb-3"><span className="text-xs font-black">Size / stitching</span><button onClick={()=>setGuide(true)} className="text-[10px] font-black text-[#a48348] flex items-center gap-1"><Ruler size={13}/> Size guide</button></div><div className="grid grid-cols-2 gap-2">{selectedProduct.sizes.map((s:string)=><button key={s} onClick={()=>setSize(s)} className={`rounded-xl border px-3 py-3 text-[10px] font-bold text-left ${size===s?'border-[#0b201b] bg-[#0b201b] text-white':'border-[#d8d0c1] bg-white text-[#4d5952]'}`}>{s}</button>)}</div></div>
          <div className="flex gap-3"><div className="flex items-center rounded-xl border border-[#d8d0c1] bg-white"><button onClick={()=>setQty(q=>Math.max(1,q-1))} className="p-3"><Minus size={14}/></button><span className="w-8 text-center text-xs font-black">{qty}</span><button onClick={()=>setQty(q=>q+1)} className="p-3"><Plus size={14}/></button></div><button onClick={()=>addToCart(selectedProduct,size,color,qty)} className="flex-1 rounded-xl bg-[#0b201b] hover:bg-[#15382f] text-white py-3 font-black text-xs flex items-center justify-center gap-2 shadow-lg"><ShoppingBag size={17}/> Add to bag</button></div>
          <a href={`https://wa.me/923001234567?text=${msg}`} target="_blank" rel="noreferrer" className="w-full rounded-xl border border-[#b8d2c0] bg-[#eef7f0] text-[#214e35] py-3.5 font-black text-xs flex items-center justify-center gap-2"><MessageCircle size={17}/> Order via WhatsApp</a>
        </div>
        <div className="grid grid-cols-3 gap-2 mt-7"><div className="rounded-xl bg-white border border-[#e9e3d8] p-3"><Truck size={15} className="text-[#a48348]"/><div className="text-[9px] font-black mt-2">Pakistan delivery</div></div><div className="rounded-xl bg-white border border-[#e9e3d8] p-3"><ShieldCheck size={15} className="text-[#a48348]"/><div className="text-[9px] font-black mt-2">Quality checked</div></div><div className="rounded-xl bg-white border border-[#e9e3d8] p-3"><Share2 size={15} className="text-[#a48348]"/><div className="text-[9px] font-black mt-2">Easy returns</div></div></div>
      </div>
    </div>
    {guide&&<div className="fixed inset-0 z-50 bg-[#0b201b]/60 backdrop-blur-sm flex items-center justify-center p-4"><div className="w-full max-w-md rounded-[24px] bg-[#fbfaf7] p-6 shadow-2xl animate-fade-up"><div className="flex items-center justify-between"><h2 className="serif text-2xl">Size guide</h2><button onClick={()=>setGuide(false)} className="rounded-full bg-white p-2"><X size={17}/></button></div><p className="text-xs text-[#707873] mt-2">Use your usual Pakistani ready-to-wear size. For stitched pieces, compare chest and shoulder measurements before ordering.</p><div className="mt-5 overflow-hidden rounded-xl border border-[#e9e3d8]"><table className="w-full text-xs"><thead className="bg-[#f2ede3]"><tr><th className="p-3 text-left">Size</th><th className="p-3 text-left">Chest</th><th className="p-3 text-left">Shoulder</th></tr></thead><tbody>{[['S','38–40','17'],['M','40–42','18'],['L','42–44','19'],['XL','44–46','20']].map(r=><tr key={r[0]} className="border-t border-[#eee8dc]"><td className="p-3 font-bold">{r[0]}</td><td className="p-3">{r[1]} in</td><td className="p-3">{r[2]} in</td></tr>)}</tbody></table></div></div></div>}
  </div>;
}
