"use client";
import React,{useContext,useEffect} from "react";
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2, X, Tag, Truck } from "lucide-react";
import { AppContext } from "@/components/store/AppProvider";

export default function CartDrawer(){
 const {isCartOpen,setIsCartOpen,cart,updateCartQty,removeFromCart,cartSubtotal,discountAmount,shippingFee,grandTotal,couponInput,setCouponInput,couponMessage,applyPromoCode,setActiveTab}=useContext(AppContext);
 useEffect(()=>{if(!isCartOpen)return;const f=(e:KeyboardEvent)=>e.key==='Escape'&&setIsCartOpen(false);window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[isCartOpen,setIsCartOpen]);
 if(!isCartOpen)return null;
 return <div className="fixed inset-0 z-50 bg-[#0b201b]/55 backdrop-blur-sm" onMouseDown={()=>setIsCartOpen(false)}><aside onMouseDown={e=>e.stopPropagation()} className="absolute right-0 top-0 h-full w-full sm:max-w-[460px] bg-[#fbfaf7] shadow-2xl flex flex-col animate-fade-up">
  <div className="px-5 py-5 border-b border-[#e9e3d8] flex items-center justify-between"><div><div className="eyebrow">Your selection</div><h2 className="serif text-2xl mt-1">Shopping bag <span className="text-sm font-sans text-[#8a918c]">({cart.reduce((s:any,i:any)=>s+i.quantity,0)})</span></h2></div><button onClick={()=>setIsCartOpen(false)} className="rounded-full bg-white border border-[#e9e3d8] p-2.5"><X size={18}/></button></div>
  {cart.length===0?<div className="flex-1 flex items-center justify-center text-center p-8"><div><div className="w-16 h-16 mx-auto rounded-full bg-[#f4ead8] flex items-center justify-center"><ShoppingBag size={25}/></div><h3 className="serif text-xl mt-4">Your bag is empty</h3><p className="text-xs text-[#7b827d] mt-2">Discover something woven for you.</p><button onClick={()=>{setIsCartOpen(false);setActiveTab('shop')}} className="mt-5 rounded-full bg-[#0b201b] text-white px-5 py-3 text-xs font-black">Shop collections</button></div></div>:<>
   <div className="px-5 py-4 bg-[#f1eee7] border-b border-[#e5ded1] flex items-center gap-2 text-[10px] font-bold"><Truck size={15} className="text-[#a48348]"/> Free delivery when your order reaches Rs. 5,000</div>
   <div className="flex-1 overflow-y-auto px-5 py-2">{cart.map((item:any,idx:number)=><div key={`${item.product.id}-${idx}`} className="py-5 border-b border-[#e9e3d8] flex gap-3"><img src={item.product.image} alt={item.product.name} className="w-[78px] h-[96px] object-cover rounded-xl bg-[#eee9df]"/><div className="min-w-0 flex-1"><div className="flex gap-2 justify-between"><h4 className="text-xs font-black leading-5 line-clamp-2">{item.product.name}</h4><button onClick={()=>removeFromCart(idx)} aria-label="Remove item" className="text-[#9b3145]"><Trash2 size={14}/></button></div><p className="text-[10px] text-[#7b827d] mt-1">{item.size} · {item.color}</p><p className="text-sm font-black mt-2">Rs. {item.price.toLocaleString()}</p><div className="flex items-center mt-3 rounded-lg border border-[#d8d0c1] bg-white w-fit"><button onClick={()=>updateCartQty(idx,-1)} className="p-1.5"><Minus size={12}/></button><span className="w-7 text-center text-[11px] font-black">{item.quantity}</span><button onClick={()=>updateCartQty(idx,1)} className="p-1.5"><Plus size={12}/></button></div></div></div>)}</div>
   <div className="border-t border-[#e1d9cb] bg-white p-5 space-y-4"><div className="flex gap-2"><div className="relative flex-1"><Tag size={14} className="absolute left-3 top-3 text-[#8a918c]"/><input value={couponInput} onChange={e=>setCouponInput(e.target.value)} placeholder="Voucher code" className="w-full rounded-xl border border-[#d8d0c1] py-2.5 pl-9 pr-3 text-xs outline-none focus:border-[#b7924b]"/></div><button onClick={applyPromoCode} className="rounded-xl border border-[#d8d0c1] px-4 text-xs font-black">Apply</button></div>{couponMessage&&<div className="text-[10px] text-[#4d7359] font-bold">{couponMessage}</div>}
    <div className="space-y-2 text-xs"><div className="flex justify-between"><span className="text-[#737b76]">Subtotal</span><span className="font-bold">Rs. {cartSubtotal.toLocaleString()}</span></div>{discountAmount>0&&<div className="flex justify-between text-[#4d7359]"><span>Discount</span><span>- Rs. {discountAmount.toLocaleString()}</span></div>}<div className="flex justify-between"><span className="text-[#737b76]">Delivery</span><span className="font-bold">{shippingFee===0?<span className="text-[#4d7359]">FREE</span>:`Rs. ${shippingFee}`}</span></div><div className="border-t border-[#e9e3d8] pt-3 flex justify-between text-base font-black"><span>Total</span><span>Rs. {grandTotal.toLocaleString()}</span></div></div>
    <button onClick={()=>{setIsCartOpen(false);setActiveTab('checkout')}} className="w-full rounded-xl bg-[#0b201b] hover:bg-[#15382f] text-white py-3.5 text-xs font-black flex items-center justify-center gap-2">Proceed to checkout <ArrowRight size={15}/></button>
   </div>
  </>}
 </aside></div>;
}
