"use client";
import React,{useContext} from "react";
import { ArrowRight, Heart, Trash2, X } from "lucide-react";
import { AppContext } from "@/components/store/AppProvider";
export default function WishlistDrawer(){
 const {isWishlistOpen,setIsWishlistOpen,wishlist,toggleWishlist,setSelectedProduct,setActiveTab,products}=useContext(AppContext);
 if(!isWishlistOpen)return null;const items=products.filter((p:any)=>wishlist.includes(p.id));
 return <div className="fixed inset-0 z-50 bg-[#0b201b]/55 backdrop-blur-sm" onMouseDown={()=>setIsWishlistOpen(false)}><aside onMouseDown={e=>e.stopPropagation()} className="absolute right-0 top-0 h-full w-full sm:max-w-[430px] bg-[#fbfaf7] shadow-2xl flex flex-col animate-fade-up"><div className="p-5 border-b border-[#e9e3d8] flex items-center justify-between"><div><div className="eyebrow">Saved pieces</div><h2 className="serif text-2xl mt-1">Wishlist</h2></div><button onClick={()=>setIsWishlistOpen(false)} className="rounded-full bg-white border border-[#e9e3d8] p-2.5"><X size={18}/></button></div><div className="flex-1 overflow-y-auto p-5 space-y-3">{items.length===0?<div className="h-full flex items-center justify-center text-center"><div><Heart size={28} className="mx-auto text-[#b7924b]"/><h3 className="serif text-xl mt-4">Nothing saved yet</h3><p className="text-xs text-[#7b827d] mt-2">Tap the heart on a piece you love.</p></div></div>:items.map((p:any)=><div key={p.id} className="bg-white rounded-2xl border border-[#e9e3d8] p-3 flex gap-3"><img src={p.image} alt={p.name} className="w-20 h-24 object-cover rounded-xl"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><h4 className="text-xs font-black leading-5 line-clamp-2">{p.name}</h4><button onClick={()=>toggleWishlist(p.id)} className="text-[#9b3145]"><Trash2 size={14}/></button></div><div className="text-sm font-black mt-2">Rs. {p.price.toLocaleString()}</div><button onClick={()=>{setSelectedProduct(p);setIsWishlistOpen(false);setActiveTab('product-detail')}} className="mt-3 rounded-full bg-[#0b201b] text-white px-4 py-2 text-[10px] font-black flex items-center gap-1">View piece <ArrowRight size={12}/></button></div></div>)}</div></aside></div>;
}
